// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPKkZgpswqPtp44jUxvJ6_wntY_JxLuJc',
    appId: '1:394991590488:web:969518717a68f594817e2d',
    messagingSenderId: '394991590488',
    projectId: 'kbm-store-76c30',
    authDomain: 'kbm-store-76c30.firebaseapp.com',
    storageBucket: 'kbm-store-76c30.firebasestorage.app',
    measurementId: 'G-WGG9Q1E1Q1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMf_vVy840hgFCHFNhvsqdi_vVr7zzfVI',
    appId: '1:394991590488:android:7995401dc9a23cf2817e2d',
    messagingSenderId: '394991590488',
    projectId: 'kbm-store-76c30',
    storageBucket: 'kbm-store-76c30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZbf48F5B_pJvFuqyXMhI86UFJDvfvlXw',
    appId: '1:394991590488:ios:aa67c474b9fc29e6817e2d',
    messagingSenderId: '394991590488',
    projectId: 'kbm-store-76c30',
    storageBucket: 'kbm-store-76c30.firebasestorage.app',
    iosBundleId: 'com.example.venteElectronics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZbf48F5B_pJvFuqyXMhI86UFJDvfvlXw',
    appId: '1:394991590488:ios:aa67c474b9fc29e6817e2d',
    messagingSenderId: '394991590488',
    projectId: 'kbm-store-76c30',
    storageBucket: 'kbm-store-76c30.firebasestorage.app',
    iosBundleId: 'com.example.venteElectronics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPKkZgpswqPtp44jUxvJ6_wntY_JxLuJc',
    appId: '1:394991590488:web:ddcb37374eff4061817e2d',
    messagingSenderId: '394991590488',
    projectId: 'kbm-store-76c30',
    authDomain: 'kbm-store-76c30.firebaseapp.com',
    storageBucket: 'kbm-store-76c30.firebasestorage.app',
    measurementId: 'G-STTC00JH4S',
  );
}
